### ISSUE TITLE
Override application.properties

### ISSUE THREAD

**Issue by iv21dk** [VadMack/MongoDB-test-app#5]
Add possibility to override application.properties using application.local.properties.
In other words, the developer will have possibility to create new file application.local.properties in the same folder with application.properties (root field of resources) to override some properties. The file should not be tracked by git.
For example, there's server.port=8080 property that can be hardcoded in application.properties. If I want to override this property, I need to change the application.properties file that is tracked by git. I want to avoid changing repository files for customize the application configuration.
In additional: It should be possible to override test properties too.

**Comment by VadMack** [comment]
Spring Boot already has support for profile based properties.
I only added **application-local.properties** file and changed the configuration.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/63146422/149164744-f13f3ccd-0abc-4913-a426-522d43711d55.png">

**Comment by iv21dk** [comment]
Please try to resolve the issue using `@PropertySource`
